import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { ScanReport } from "@/lib/types";

const styles = StyleSheet.create({
  page: { fontFamily: "Helvetica", padding: 48, backgroundColor: "#FFFFFF", fontSize: 10, color: "#1C1C1A" },
  header: { marginBottom: 32 },
  title: { fontSize: 22, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#6B7280" },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 13, fontFamily: "Helvetica-Bold", marginBottom: 10, paddingBottom: 4, borderBottomWidth: 1, borderBottomColor: "#E5E7EB" },
  scoreRow: { flexDirection: "row", gap: 12, marginBottom: 12 },
  scoreCard: { flex: 1, backgroundColor: "#F8F7F4", borderRadius: 8, padding: 12 },
  scoreLabel: { fontSize: 9, color: "#6B7280", marginBottom: 4 },
  scoreValue: { fontSize: 22, fontFamily: "Helvetica-Bold" },
  finding: { marginBottom: 8, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: "#F3F4F6" },
  findingTitle: { fontFamily: "Helvetica-Bold", fontSize: 10, marginBottom: 2 },
  findingDesc: { fontSize: 9, color: "#6B7280", lineHeight: 1.4 },
  badge: { fontSize: 8, color: "#6B7280", marginBottom: 2 },
  rec: { marginBottom: 10, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: "#F3F4F6" },
  recTitle: { fontFamily: "Helvetica-Bold", fontSize: 10, marginBottom: 2 },
  recBody: { fontSize: 9, color: "#6B7280", lineHeight: 1.4 },
  footer: { position: "absolute", bottom: 32, left: 48, right: 48, flexDirection: "row", justifyContent: "space-between", fontSize: 8, color: "#9CA3AF" },
});

function scoreColor(score: number): string {
  if (score >= 80) return "#22C55E";
  if (score >= 60) return "#FBBF24";
  return "#EF4444";
}

function ReportDocument({ report }: { report: ScanReport }) {
  const highFindings = report.findings.filter((f) => f.severity === "high");
  const medFindings = report.findings.filter((f) => f.severity === "medium");

  return (
    <Document title={`Revilo Report — ${report.workspaceName}`} author="Revilo">
      {/* Cover page */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Design System Report</Text>
          <Text style={styles.subtitle}>
            {report.workspaceName} · {new Date(report.scannedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
          </Text>
        </View>

        {/* Scores */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Overall Scores</Text>
          <View style={styles.scoreRow}>
            <View style={styles.scoreCard}>
              <Text style={styles.scoreLabel}>Alignment</Text>
              <Text style={[styles.scoreValue, { color: scoreColor(report.alignment.overall) }]}>{report.alignment.overall}</Text>
            </View>
            <View style={styles.scoreCard}>
              <Text style={styles.scoreLabel}>Adoption</Text>
              <Text style={[styles.scoreValue, { color: scoreColor(report.adoption.overall) }]}>{report.adoption.overall}</Text>
            </View>
            <View style={styles.scoreCard}>
              <Text style={styles.scoreLabel}>Architecture</Text>
              <Text style={[styles.scoreValue, { color: scoreColor(report.architecture.overall) }]}>{report.architecture.overall}</Text>
            </View>
          </View>
          <View style={styles.scoreCard}>
            <Text style={styles.scoreLabel}>Components scanned</Text>
            <Text style={{ fontSize: 14, fontFamily: "Helvetica-Bold" }}>{report.componentsScanned}</Text>
          </View>
        </View>

        {/* High severity findings */}
        {highFindings.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>High Priority Findings ({highFindings.length})</Text>
            {highFindings.slice(0, 15).map((f) => (
              <View key={f.id} style={styles.finding}>
                <Text style={styles.badge}>{f.type.replace(/_/g, " ").toUpperCase()}</Text>
                <Text style={styles.findingTitle}>{f.title}</Text>
                <Text style={styles.findingDesc}>{f.description}</Text>
              </View>
            ))}
          </View>
        )}

        <View style={styles.footer}>
          <Text>Generated by Revilo · revilo-three.vercel.app</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      {/* Recommendations page */}
      {report.recommendations.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Recommendations</Text>
          {report.recommendations.map((rec) => (
            <View key={rec.id} style={styles.rec}>
              <Text style={styles.badge}>
                {rec.tier.replace("_", " ").toUpperCase()} · Impact: {rec.impact} · Effort: {rec.effort}
              </Text>
              <Text style={styles.recTitle}>{rec.title}</Text>
              <Text style={styles.recBody}>{rec.whyItMatters}</Text>
              <Text style={[styles.recBody, { marginTop: 3, color: "#374151" }]}>→ {rec.suggestedFix}</Text>
            </View>
          ))}
          <View style={styles.footer}>
            <Text>Generated by Revilo · revilo-three.vercel.app</Text>
            <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
          </View>
        </Page>
      )}

      {/* Medium findings page */}
      {medFindings.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Medium Priority Findings ({medFindings.length})</Text>
          {medFindings.slice(0, 20).map((f) => (
            <View key={f.id} style={styles.finding}>
              <Text style={styles.badge}>{f.type.replace(/_/g, " ").toUpperCase()}</Text>
              <Text style={styles.findingTitle}>{f.title}</Text>
              <Text style={styles.findingDesc}>{f.description}</Text>
            </View>
          ))}
          <View style={styles.footer}>
            <Text>Generated by Revilo · revilo-three.vercel.app</Text>
            <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
          </View>
        </Page>
      )}
    </Document>
  );
}

export async function generateReportPdf(report: ScanReport): Promise<Buffer> {
  return renderToBuffer(<ReportDocument report={report} />);
}
